nutritions_tab: dict[str, dict] = {
    # ── Mains & Stews ─────────────────────────────────────────────────────────
    "tajine":              {"calories": 420, "carbs_g": 22, "protein_g": 31, "fat_g": 18, "sugar_g":  4, "fibre_g": 5},
    "couscous":            {"calories": 380, "carbs_g": 58, "protein_g": 14, "fat_g":  9, "sugar_g":  3, "fibre_g": 6},
    "rfissa":              {"calories": 470, "carbs_g": 48, "protein_g": 28, "fat_g": 16, "sugar_g":  4, "fibre_g": 5},
    "mrouzia":             {"calories": 490, "carbs_g": 38, "protein_g": 30, "fat_g": 22, "sugar_g": 18, "fibre_g": 3},
    "tanjia":              {"calories": 540, "carbs_g":  4, "protein_g": 48, "fat_g": 36, "sugar_g":  1, "fibre_g": 1},
    "mechoui":             {"calories": 520, "carbs_g":  0, "protein_g": 45, "fat_g": 36, "sugar_g":  0, "fibre_g": 0},
    "kefta":               {"calories": 350, "carbs_g":  6, "protein_g": 28, "fat_g": 24, "sugar_g":  2, "fibre_g": 1},
    "kefta_tagine":        {"calories": 390, "carbs_g": 10, "protein_g": 27, "fat_g": 26, "sugar_g":  4, "fibre_g": 2},
    "chermoula_fish":      {"calories": 280, "carbs_g":  5, "protein_g": 34, "fat_g": 13, "sugar_g":  1, "fibre_g": 1},
    "sardines_grillees":   {"calories": 210, "carbs_g":  0, "protein_g": 26, "fat_g": 12, "sugar_g":  0, "fibre_g": 0},
    "hout_chermoula":      {"calories": 260, "carbs_g":  6, "protein_g": 30, "fat_g": 12, "sugar_g":  2, "fibre_g": 1},
    "chicken_msfouf":      {"calories": 430, "carbs_g": 44, "protein_g": 29, "fat_g": 14, "sugar_g":  6, "fibre_g": 4},
    "tangia_marrakchia":   {"calories": 560, "carbs_g":  5, "protein_g": 50, "fat_g": 38, "sugar_g":  1, "fibre_g": 1},
    "dafina":              {"calories": 500, "carbs_g": 42, "protein_g": 32, "fat_g": 18, "sugar_g":  8, "fibre_g": 8},
    "lamb_couscous":       {"calories": 480, "carbs_g": 55, "protein_g": 28, "fat_g": 14, "sugar_g":  5, "fibre_g": 7},
    "chicken_tagine_olives":{"calories": 410, "carbs_g": 12, "protein_g": 35, "fat_g": 22, "sugar_g":  2, "fibre_g": 3},
    "tagine_prunes":       {"calories": 460, "carbs_g": 36, "protein_g": 30, "fat_g": 20, "sugar_g": 20, "fibre_g": 4},
    "tagine_citron":       {"calories": 390, "carbs_g":  8, "protein_g": 36, "fat_g": 22, "sugar_g":  2, "fibre_g": 2},
    "seffa":               {"calories": 520, "carbs_g": 68, "protein_g": 18, "fat_g": 18, "sugar_g": 14, "fibre_g": 3},
    "couscous_tfaya":      {"calories": 510, "carbs_g": 62, "protein_g": 22, "fat_g": 16, "sugar_g": 16, "fibre_g": 6},

    # ── Soups ─────────────────────────────────────────────────────────────────
    "harira":              {"calories": 210, "carbs_g": 28, "protein_g": 11, "fat_g":  5, "sugar_g":  4, "fibre_g": 7},
    "bissara":             {"calories": 180, "carbs_g": 26, "protein_g": 10, "fat_g":  5, "sugar_g":  2, "fibre_g": 8},
    "loubia":              {"calories": 230, "carbs_g": 34, "protein_g": 12, "fat_g":  5, "sugar_g":  3, "fibre_g": 9},
    "lentil_soup":         {"calories": 200, "carbs_g": 30, "protein_g": 12, "fat_g":  4, "sugar_g":  3, "fibre_g": 8},
    "chorba":              {"calories": 190, "carbs_g": 24, "protein_g": 10, "fat_g":  5, "sugar_g":  4, "fibre_g": 5},
    "smen_soup":           {"calories": 160, "carbs_g": 18, "protein_g":  6, "fat_g":  7, "sugar_g":  2, "fibre_g": 3},
    "chickpea_soup":       {"calories": 220, "carbs_g": 32, "protein_g": 10, "fat_g":  5, "sugar_g":  3, "fibre_g": 7},

    # ── Salads & Appetisers ───────────────────────────────────────────────────
    "zaalouk":             {"calories": 130, "carbs_g": 14, "protein_g":  2, "fat_g":  8, "sugar_g":  6, "fibre_g": 4},
    "taktouka":            {"calories": 110, "carbs_g": 12, "protein_g":  3, "fat_g":  6, "sugar_g":  5, "fibre_g": 3},
    "makouda":             {"calories": 200, "carbs_g": 24, "protein_g":  5, "fat_g": 10, "sugar_g":  1, "fibre_g": 2},
    "briouats":            {"calories": 320, "carbs_g": 28, "protein_g": 14, "fat_g": 17, "sugar_g":  2, "fibre_g": 2},
    "beetroot_salad":      {"calories":  80, "carbs_g": 14, "protein_g":  2, "fat_g":  3, "sugar_g": 10, "fibre_g": 3},
    "carrot_salad":        {"calories":  90, "carbs_g": 15, "protein_g":  1, "fat_g":  3, "sugar_g":  8, "fibre_g": 3},
    "cucumber_salad":      {"calories":  50, "carbs_g":  7, "protein_g":  1, "fat_g":  2, "sugar_g":  3, "fibre_g": 1},
    "tomato_cumin_salad":  {"calories":  70, "carbs_g":  9, "protein_g":  2, "fat_g":  3, "sugar_g":  5, "fibre_g": 2},
    "potato_salad_chermoula":{"calories":180, "carbs_g": 26, "protein_g":  3, "fat_g":  7, "sugar_g":  2, "fibre_g": 3},
    "fried_eggplant":      {"calories": 160, "carbs_g": 12, "protein_g":  2, "fat_g": 11, "sugar_g":  4, "fibre_g": 4},
    "mechouia_salad":      {"calories": 120, "carbs_g": 13, "protein_g":  3, "fat_g":  7, "sugar_g":  5, "fibre_g": 3},
    "pepper_salad":        {"calories":  95, "carbs_g": 11, "protein_g":  2, "fat_g":  5, "sugar_g":  5, "fibre_g": 3},
    "argan_amlou":         {"calories": 490, "carbs_g": 20, "protein_g": 12, "fat_g": 42, "sugar_g": 14, "fibre_g": 4},

    # ── Pastries & Street Food ────────────────────────────────────────────────
    "bastilla":            {"calories": 510, "carbs_g": 42, "protein_g": 26, "fat_g": 22, "sugar_g":  6, "fibre_g": 2},
    "bastilla_seafood":    {"calories": 470, "carbs_g": 40, "protein_g": 24, "fat_g": 20, "sugar_g":  4, "fibre_g": 2},
    "msemen":              {"calories": 290, "carbs_g": 44, "protein_g":  7, "fat_g":  9, "sugar_g":  1, "fibre_g": 1},
    "meloui":              {"calories": 270, "carbs_g": 40, "protein_g":  6, "fat_g": 10, "sugar_g":  1, "fibre_g": 1},
    "rghaif":              {"calories": 300, "carbs_g": 42, "protein_g":  7, "fat_g": 12, "sugar_g":  1, "fibre_g": 1},
    "baghrir":             {"calories": 220, "carbs_g": 38, "protein_g":  7, "fat_g":  4, "sugar_g":  2, "fibre_g": 2},
    "sfenj":               {"calories": 310, "carbs_g": 46, "protein_g":  6, "fat_g": 12, "sugar_g":  4, "fibre_g": 1},
    "khobz":               {"calories": 260, "carbs_g": 50, "protein_g":  8, "fat_g":  3, "sugar_g":  1, "fibre_g": 2},
    "harcha":              {"calories": 340, "carbs_g": 46, "protein_g":  7, "fat_g": 14, "sugar_g":  2, "fibre_g": 2},
    "maakouda_sandwich":   {"calories": 410, "carbs_g": 52, "protein_g": 10, "fat_g": 18, "sugar_g":  3, "fibre_g": 3},
    "merguez_sandwich":    {"calories": 430, "carbs_g": 38, "protein_g": 22, "fat_g": 20, "sugar_g":  3, "fibre_g": 2},
    "kefta_sandwich":      {"calories": 420, "carbs_g": 36, "protein_g": 24, "fat_g": 18, "sugar_g":  3, "fibre_g": 2},
    "sandwich_sardine":    {"calories": 350, "carbs_g": 34, "protein_g": 20, "fat_g": 13, "sugar_g":  2, "fibre_g": 2},
    "briouat_cheese":      {"calories": 290, "carbs_g": 22, "protein_g": 10, "fat_g": 18, "sugar_g":  1, "fibre_g": 1},
    "briouat_kefta":       {"calories": 310, "carbs_g": 22, "protein_g": 14, "fat_g": 19, "sugar_g":  2, "fibre_g": 1},
    "harira_with_dates":   {"calories": 260, "carbs_g": 42, "protein_g": 11, "fat_g":  5, "sugar_g": 14, "fibre_g": 7},

    # ── Sweets & Desserts ─────────────────────────────────────────────────────
    "chebakia":            {"calories": 240, "carbs_g": 31, "protein_g":  3, "fat_g": 12, "sugar_g": 18, "fibre_g": 1},
    "sellou":              {"calories": 480, "carbs_g": 52, "protein_g": 12, "fat_g": 26, "sugar_g": 24, "fibre_g": 5},
    "kaab_el_ghazal":      {"calories": 190, "carbs_g": 24, "protein_g":  3, "fat_g": 10, "sugar_g": 14, "fibre_g": 1},
    "ghriba":              {"calories": 160, "carbs_g": 20, "protein_g":  3, "fat_g":  8, "sugar_g": 12, "fibre_g": 1},
    "fekkas":              {"calories": 150, "carbs_g": 22, "protein_g":  3, "fat_g":  6, "sugar_g":  8, "fibre_g": 1},
    "halwa_chebakia":      {"calories": 230, "carbs_g": 30, "protein_g":  3, "fat_g": 11, "sugar_g": 18, "fibre_g": 1},
    "mhancha":             {"calories": 280, "carbs_g": 30, "protein_g":  5, "fat_g": 16, "sugar_g": 18, "fibre_g": 2},
    "pastilla_sucrée":     {"calories": 340, "carbs_g": 38, "protein_g":  7, "fat_g": 18, "sugar_g": 16, "fibre_g": 2},
    "roz_bil_hlib":        {"calories": 220, "carbs_g": 38, "protein_g":  6, "fat_g":  5, "sugar_g": 18, "fibre_g": 0},
    "seffa_sucrée":        {"calories": 430, "carbs_g": 62, "protein_g":  8, "fat_g": 16, "sugar_g": 20, "fibre_g": 2},
    "orange_cinnamon":     {"calories":  80, "carbs_g": 18, "protein_g":  1, "fat_g":  1, "sugar_g": 15, "fibre_g": 3},
    "watermelon_mint":     {"calories":  60, "carbs_g": 14, "protein_g":  1, "fat_g":  0, "sugar_g": 12, "fibre_g": 1},
    "date_almond_balls":   {"calories": 200, "carbs_g": 26, "protein_g":  4, "fat_g": 10, "sugar_g": 20, "fibre_g": 3},
    "coconut_ghriba":      {"calories": 170, "carbs_g": 22, "protein_g":  2, "fat_g":  9, "sugar_g": 13, "fibre_g": 2},
    "almond_briouat":      {"calories": 260, "carbs_g": 26, "protein_g":  5, "fat_g": 16, "sugar_g": 14, "fibre_g": 2},

    # ── Beverages ─────────────────────────────────────────────────────────────
    "mint_tea":            {"calories":  45, "carbs_g": 11, "protein_g":  0, "fat_g":  0, "sugar_g": 11, "fibre_g": 0},
    "avocado_smoothie":    {"calories": 280, "carbs_g": 30, "protein_g":  4, "fat_g": 17, "sugar_g": 18, "fibre_g": 5},
    "almond_milk":         {"calories": 160, "carbs_g": 22, "protein_g":  5, "fat_g":  6, "sugar_g": 14, "fibre_g": 2},
    "leben":               {"calories": 110, "carbs_g": 12, "protein_g":  8, "fat_g":  3, "sugar_g": 10, "fibre_g": 0},
    "rosewater_lemonade":  {"calories":  70, "carbs_g": 18, "protein_g":  0, "fat_g":  0, "sugar_g": 16, "fibre_g": 0},

    # ── Condiments, Dips & Pantry ─────────────────────────────────────────────
    "chermoula_sauce":     {"calories":  90, "carbs_g":  3, "protein_g":  1, "fat_g":  8, "sugar_g":  1, "fibre_g": 1},
    "harissa":             {"calories":  45, "carbs_g":  5, "protein_g":  1, "fat_g":  3, "sugar_g":  2, "fibre_g": 2},
    "preserved_lemon":     {"calories":  20, "carbs_g":  4, "protein_g":  0, "fat_g":  0, "sugar_g":  2, "fibre_g": 1},
    "argan_oil_drizzle":   {"calories": 120, "carbs_g":  0, "protein_g":  0, "fat_g": 14, "sugar_g":  0, "fibre_g": 0},
    "smen":                {"calories": 720, "carbs_g":  0, "protein_g":  1, "fat_g": 80, "sugar_g":  0, "fibre_g": 0},
    "olive_tapenade":      {"calories": 150, "carbs_g":  4, "protein_g":  1, "fat_g": 14, "sugar_g":  0, "fibre_g": 2},
    "ras_el_hanout_lamb":  {"calories": 390, "carbs_g":  5, "protein_g": 34, "fat_g": 25, "sugar_g":  1, "fibre_g": 1},

    # ── Grains, Legumes & Sides ───────────────────────────────────────────────
    "plain_couscous":      {"calories": 180, "carbs_g": 36, "protein_g":  6, "fat_g":  0, "sugar_g":  0, "fibre_g": 2},
    "khobz_semolina":      {"calories": 280, "carbs_g": 54, "protein_g":  9, "fat_g":  3, "sugar_g":  1, "fibre_g": 3},
    "fava_bean_stew":      {"calories": 210, "carbs_g": 30, "protein_g": 13, "fat_g":  4, "sugar_g":  2, "fibre_g": 9},
    "chickpea_stew":       {"calories": 240, "carbs_g": 36, "protein_g": 11, "fat_g":  5, "sugar_g":  3, "fibre_g": 8},
    "lentils_cumin":       {"calories": 200, "carbs_g": 32, "protein_g": 11, "fat_g":  3, "sugar_g":  2, "fibre_g": 8},
    "steamed_vegetables":  {"calories":  80, "carbs_g": 14, "protein_g":  3, "fat_g":  1, "sugar_g":  6, "fibre_g": 5},
    "spiced_potatoes":     {"calories": 190, "carbs_g": 30, "protein_g":  4, "fat_g":  6, "sugar_g":  2, "fibre_g": 3},
    "roasted_peppers":     {"calories":  90, "carbs_g": 10, "protein_g":  2, "fat_g":  5, "sugar_g":  5, "fibre_g": 3},
    "msemen_honey_butter": {"calories": 370, "carbs_g": 50, "protein_g":  7, "fat_g": 16, "sugar_g": 18, "fibre_g": 1},
    "pan_fried_liver":     {"calories": 290, "carbs_g":  5, "protein_g": 28, "fat_g": 17, "sugar_g":  1, "fibre_g": 1},
    "lamb_brochette":      {"calories": 330, "carbs_g":  3, "protein_g": 32, "fat_g": 20, "sugar_g":  1, "fibre_g": 0},
    "chicken_brochette":   {"calories": 240, "carbs_g":  2, "protein_g": 30, "fat_g": 12, "sugar_g":  1, "fibre_g": 0},
    "merguez":             {"calories": 310, "carbs_g":  2, "protein_g": 18, "fat_g": 25, "sugar_g":  1, "fibre_g": 0},
    "camel_tajine":        {"calories": 400, "carbs_g": 18, "protein_g": 38, "fat_g": 16, "sugar_g":  4, "fibre_g": 3},
    "rabbit_tajine":       {"calories": 360, "carbs_g": 14, "protein_g": 34, "fat_g": 16, "sugar_g":  3, "fibre_g": 3},
    "pigeon_pastilla":     {"calories": 530, "carbs_g": 44, "protein_g": 28, "fat_g": 24, "sugar_g":  8, "fibre_g": 2},
    "snail_soup":          {"calories": 140, "carbs_g":  8, "protein_g": 14, "fat_g":  5, "sugar_g":  1, "fibre_g": 1},
    "fried_whiting":       {"calories": 240, "carbs_g": 12, "protein_g": 22, "fat_g": 11, "sugar_g":  0, "fibre_g": 0},
    "shrimp_chermoula":    {"calories": 200, "carbs_g":  5, "protein_g": 26, "fat_g":  9, "sugar_g":  1, "fibre_g": 1},
    "octopus_tagine":      {"calories": 230, "carbs_g": 10, "protein_g": 28, "fat_g":  8, "sugar_g":  2, "fibre_g": 2},
}