ingredients_price = {
    # ── Proteins ──────────────────────────────────────────────────────
    "chicken":          {"price_mad": 15,   "unit": "kg",     "notes": "whole chicken, souk price"},
    "chicken breast":   {"price_mad": 50,   "unit": "kg",     "notes": "boneless"},
    "lamb":             {"price_mad": 75,   "unit": "kg",     "notes": "bone-in, varies by season; avg of two sources"},
    "beef":             {"price_mad": 85,   "unit": "kg",     "notes": "average cut"},
    "kefta":            {"price_mad": 85,   "unit": "kg",     "notes": "minced beef/lamb mix"},
    "merguez":          {"price_mad": 60,   "unit": "kg",     "notes": "spiced lamb/beef sausage"},
    "rabbit":           {"price_mad": 45,   "unit": "kg",     "notes": ""},
    "fish":             {"price_mad": 30,   "unit": "kg",     "notes": "sardines/mackerel, coastal average"},
    "sardines":         {"price_mad": 12,   "unit": "kg",     "notes": "fresh, coastal"},
    "sea bass":         {"price_mad": 60,   "unit": "kg",     "notes": ""},
    "tuna":             {"price_mad": 40,   "unit": "kg",     "notes": ""},
    "squid":            {"price_mad": 50,   "unit": "kg",     "notes": ""},
    "anchovies":        {"price_mad": 25,   "unit": "kg",     "notes": ""},
    "shrimp":           {"price_mad": 85,   "unit": "kg",     "notes": "fresh, coastal markets; avg of two sources"},
    "egg":              {"price_mad": 1.25, "unit": "unit",   "notes": "≈15 MAD/dozen"},
    # ── Legumes ───────────────────────────────────────────────────────
    "chickpeas":        {"price_mad": 12,   "unit": "kg",     "notes": "dried; avg of two sources"},
    "lentils":          {"price_mad": 9,    "unit": "kg",     "notes": "dried, red or green; avg of two sources"},
    "broad beans":      {"price_mad": 8.5,  "unit": "kg",     "notes": "dried fava beans; avg of two sources"},
    "white beans":      {"price_mad": 10,   "unit": "kg",     "notes": "dried"},
    "black-eyed peas":  {"price_mad": 10,   "unit": "kg",     "notes": "dried"},
    # ── Grains & Bread ────────────────────────────────────────────────
    "couscous":         {"price_mad": 10,   "unit": "kg",     "notes": "medium grain; avg of two sources"},
    "flour":            {"price_mad": 4.5,  "unit": "kg",     "notes": "white wheat flour; avg of two sources"},
    "semolina":         {"price_mad": 6,    "unit": "kg",     "notes": "fine, for msemen/harcha"},
    "rice":             {"price_mad": 10.5, "unit": "kg",     "notes": "local variety; avg of two sources"},
    "bread":            {"price_mad": 1.2,  "unit": "unit",   "notes": "khobz standard loaf"},
    "msemen":           {"price_mad": 2,    "unit": "unit",   "notes": "per piece"},
    "harcha":           {"price_mad": 1.5,  "unit": "unit",   "notes": "per piece"},
    "phyllo dough":     {"price_mad": 25,   "unit": "pack",   "notes": "warqa/brick pastry"},
    "yeast":            {"price_mad": 5,    "unit": "pack",   "notes": ""},
    "baking powder":    {"price_mad": 5,    "unit": "pack",   "notes": ""},
    # ── Vegetables ───────────────────────────────────────────────────
    "tomato":           {"price_mad": 7,    "unit": "kg",     "notes": "seasonal average; avg of two sources"},
    "onion":            {"price_mad": 8,    "unit": "kg",     "notes": "avg of two sources"},
    "garlic":           {"price_mad": 17.5, "unit": "kg",     "notes": "local; avg of two sources"},
    "potato":           {"price_mad": 6.75, "unit": "kg",     "notes": "local variety; avg of two sources"},
    "carrot":           {"price_mad": 5.5,  "unit": "kg",     "notes": "avg of two sources"},
    "zucchini":         {"price_mad": 6.5,  "unit": "kg",     "notes": "courgette; avg of two sources"},
    "eggplant":         {"price_mad": 7,    "unit": "kg",     "notes": "aubergine; avg of two sources"},
    "pepper":           {"price_mad": 7.5,  "unit": "kg",     "notes": "green/red bell pepper; avg of two sources"},
    "spinach":          {"price_mad": 4.5,  "unit": "kg",     "notes": "avg of two sources"},
    "turnip":           {"price_mad": 5.5,  "unit": "kg",     "notes": "navet; avg of two sources"},
    "celery":           {"price_mad": 2,    "unit": "bunch",  "notes": "large bunch"},
    "green beans":      {"price_mad": 14,   "unit": "kg",     "notes": "haricots verts; avg of two sources"},
    "peas":             {"price_mad": 6.5,  "unit": "kg",     "notes": "fresh or frozen; avg of two sources"},
    "artichoke":        {"price_mad": 15,   "unit": "kg",     "notes": "seasonal (winter/spring)"},
    "leek":             {"price_mad": 6,    "unit": "kg",     "notes": ""},
    "cabbage":          {"price_mad": 3,    "unit": "kg",     "notes": ""},
    "olives":           {"price_mad": 20,   "unit": "kg",     "notes": "mixed table olives"},
    "beldi olives":     {"price_mad": 25,   "unit": "kg",     "notes": "aged/cured"},
    # ── Fresh Herbs ──────────────────────────────────────────────────
    "parsley":          {"price_mad": 1,    "unit": "bunch",  "notes": "large bunch"},
    "coriander":        {"price_mad": 1,    "unit": "bunch",  "notes": "large bunch"},
    "mint":             {"price_mad": 1.5,  "unit": "bunch",  "notes": "for tea"},
    # ── Fats & Dairy ─────────────────────────────────────────────────
    "olive oil":        {"price_mad": 55,   "unit": "litre",  "notes": "extra virgin, local; avg of two sources"},
    "argan oil":        {"price_mad": 250,  "unit": "litre",  "notes": "culinary grade; avg of two sources"},
    "butter":           {"price_mad": 77.5, "unit": "kg",     "notes": "avg of two sources"},
    "smen":             {"price_mad": 115,  "unit": "kg",     "notes": "aged fermented butter; avg of two sources"},
    "milk":             {"price_mad": 9,    "unit": "litre",  "notes": "pasteurised; avg of two sources"},
    "cream":            {"price_mad": 22.5, "unit": "litre",  "notes": "cooking cream; avg of two sources"},
    "yogurt":           {"price_mad": 8,    "unit": "litre",  "notes": ""},
    "goat cheese":      {"price_mad": 80,   "unit": "kg",     "notes": ""},
    # ── Fruits ───────────────────────────────────────────────────────
    "lemon":            {"price_mad": 5,    "unit": "kg",     "notes": ""},
    "preserved lemon":  {"price_mad": 30,   "unit": "kg",     "notes": "citrons confits"},
    "orange":           {"price_mad": 4,    "unit": "kg",     "notes": ""},
    "pomegranate":      {"price_mad": 12,   "unit": "kg",     "notes": "seasonal"},
    "quince":           {"price_mad": 10,   "unit": "kg",     "notes": "seasonal"},
    "grape":            {"price_mad": 10,   "unit": "kg",     "notes": ""},
    # ── Nuts & Dried Fruits ──────────────────────────────────────────
    "almond":           {"price_mad": 80,   "unit": "kg",     "notes": "shelled"},
    "almond paste":     {"price_mad": 100,  "unit": "kg",     "notes": "for pastries"},
    "walnut":           {"price_mad": 70,   "unit": "kg",     "notes": "shelled"},
    "pistachio":        {"price_mad": 90,   "unit": "kg",     "notes": "shelled"},
    "raisin":           {"price_mad": 30,   "unit": "kg",     "notes": "avg of two sources"},
    "date":             {"price_mad": 35,   "unit": "kg",     "notes": "Medjool higher; avg of two sources"},
    "fig":              {"price_mad": 20,   "unit": "kg",     "notes": "dried"},
    "prune":            {"price_mad": 32.5, "unit": "kg",     "notes": "avg of two sources"},
    "dried apricot":    {"price_mad": 15,   "unit": "kg",     "notes": ""},
    # ── Spices ───────────────────────────────────────────────────────
    "cumin":            {"price_mad": 55,   "unit": "kg",     "notes": "whole or ground; avg of two sources"},
    "cinnamon":         {"price_mad": 65,   "unit": "kg",     "notes": "sticks or ground; avg of two sources"},
    "ginger":           {"price_mad": 35,   "unit": "kg",     "notes": "ground; avg of two sources"},
    "turmeric":         {"price_mad": 52.5, "unit": "kg",     "notes": "avg of two sources"},
    "paprika":          {"price_mad": 42.5, "unit": "kg",     "notes": "sweet red; avg of two sources"},
    "saffron":          {"price_mad": 7000, "unit": "kg",     "notes": "Taliouine saffron; avg of two sources (~7 MAD/g)"},
    "ras el hanout":    {"price_mad": 100,  "unit": "kg",     "notes": "blend, varies by spice shop; avg of two sources"},
    "harissa":          {"price_mad": 25,   "unit": "kg",     "notes": "fresh paste; avg of two sources"},
    "black pepper":     {"price_mad": 75,   "unit": "kg",     "notes": "avg of two sources"},
    "chili":            {"price_mad": 15,   "unit": "kg",     "notes": "fresh red chili"},
    "cayenne":          {"price_mad": 55,   "unit": "kg",     "notes": ""},
    "cloves":           {"price_mad": 150,  "unit": "kg",     "notes": ""},
    "anise":            {"price_mad": 40,   "unit": "kg",     "notes": ""},
    "caraway":          {"price_mad": 50,   "unit": "kg",     "notes": ""},
    "fenugreek":        {"price_mad": 35,   "unit": "kg",     "notes": ""},
    "thyme":            {"price_mad": 30,   "unit": "kg",     "notes": "dried"},
    "bay leaf":         {"price_mad": 15,   "unit": "pack",   "notes": ""},
    "sesame":           {"price_mad": 40,   "unit": "kg",     "notes": ""},
    # ── Condiments & Pantry ──────────────────────────────────────────
    "tomato paste":     {"price_mad": 15,   "unit": "kg",     "notes": "double concentrate; avg of two sources"},
    "honey":            {"price_mad": 100,  "unit": "kg",     "notes": "local honey, varies by type; avg of two sources"},
    "sugar":            {"price_mad": 6.5,  "unit": "kg",     "notes": "avg of two sources"},
    "powdered sugar":   {"price_mad": 8,    "unit": "kg",     "notes": ""},
    "salt":             {"price_mad": 1,    "unit": "unit",   "notes": ""},
    "rose water":       {"price_mad": 15,   "unit": "litre",  "notes": ""},
    "orange blossom":   {"price_mad": 17.5, "unit": "litre",  "notes": "eau de fleur d'oranger; avg of two sources"},
    "harira mix":       {"price_mad": 20,   "unit": "pack",   "notes": "pre-mixed dried blend"},
    # ── Beverages ────────────────────────────────────────────────────
    "green tea":        {"price_mad": 37.5, "unit": "kg",     "notes": "gunpowder tea; avg of two sources"},
    "mint tea":         {"price_mad": 30,   "unit": "pack",   "notes": "pre-packaged"},
    "coffee":           {"price_mad": 60,   "unit": "kg",     "notes": ""},
    "almond milk":      {"price_mad": 15,   "unit": "litre",  "notes": ""},
}